
import React from 'react';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';

type ReportProps = {
  reportData: {
    id: string;
    status: string;
    contentType: string;
    uploadTime: string;
    user: string;
    aiAnalysis: {
      reason: string;
      category: string;
      confidence: number;
    };
  };
  filename: string;
};

const ReportDownload = ({ reportData, filename }: ReportProps) => {
  const handleDownload = () => {
    // Format the report as a clean structured report
    const formatDate = (dateString: string) => {
      const date = new Date(dateString);
      return new Intl.DateTimeFormat('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit'
      }).format(date);
    };

    const reportContent = `
CONTENT MODERATION REPORT
=========================

REPORT ID: ${reportData.id}
REPORT DATE: ${formatDate(reportData.uploadTime)}
STATUS: ${reportData.status.toUpperCase()}

CONTENT INFORMATION:
-------------------
Content Type: ${reportData.contentType}
Uploaded By: ${reportData.user}
Upload Time: ${formatDate(reportData.uploadTime)}

AI ANALYSIS:
-----------
Category: ${reportData.aiAnalysis.category || 'Unknown'}
Confidence: ${((reportData.aiAnalysis.confidence || 0) * 100).toFixed(1)}%
Reason: ${reportData.aiAnalysis.reason || 'No reason provided'}

RECOMMENDATIONS:
--------------
${reportData.status === 'flagged' 
  ? 'This content has been flagged as potentially violating platform policies. Review is recommended.'
  : 'This content has been marked as safe and complies with platform guidelines.'}

Generated by Safe Net Content Moderation System
Report generated on: ${formatDate(new Date().toISOString())}
`;

    // Create a Blob from the report content
    const blob = new Blob([reportContent], { type: 'text/plain' });
    
    // Create a downloadable link and trigger download
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.txt`;
    document.body.appendChild(a);
    a.click();
    
    // Clean up
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };
  
  return (
    <Button variant="default" onClick={handleDownload}>
      <Download className="mr-2 h-4 w-4" />
      Download Report
    </Button>
  );
};

export default ReportDownload;
