
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etycoawagljjnlyctrfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0eWNvYXdhZ2xqam5seWN0cmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTkzMjcsImV4cCI6MjA2MzI5NTMyN30.NVgCjHwrEb5HWLkyCSn4vO0yzQy85QUn8ylfV5z1iLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage,
    detectSessionInUrl: true,
    flowType: 'implicit',
  }
});
